version: '3.4'

x-env: &x-env
  BROADCAST_DRIVER: redis
  CACHE_DRIVER: redis
  COMPOSER_HOME: /data/osuweb/.docker/.composer
  DB_HOST: db
  ES_HOST: elasticsearch:9200
  HOME: /data/osuweb/.docker
  NOTIFICATION_REDIS_HOST: redis
  REDIS_HOST: redis
  SESSION_DRIVER: redis
  YARN_CACHE_FOLDER: /data/osuweb/.docker/.yarn
  DOCKER: 1
  MODE: ${MODE:-0}
  MODE_LITERAL: ${MODE_LITERAL:-osu}

services:
  nginx:
    image: nginx:latest
    depends_on:
      - notification-server
      - php
    volumes:
      - ./docker/nginx/nginx-osu-next:/etc/nginx/conf.d/default.conf
      - .:/data/osuweb
    ports:
      - "${NGINX_PORT:-8080}:80"
  db:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
      - ./bin/db_setup.sh:/docker-entrypoint-initdb.d/db_setup.sh
      - ./docker/mysql/db_user.sql:/docker-entrypoint-initdb.d/db_user.sql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      <<: *x-env
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
  php:
    build:
      context: ./docker/php
    working_dir: /data/osuweb
    volumes:
      - .:/data/osuweb
    user: ${UID:?err}
    environment:
      <<: *x-env
    command: ['/usr/sbin/php-fpm7', '-y', '/data/osuweb/docker/php/php-fpm.conf']
  notification-server:
    build:
      context: ./docker/notification-server
    depends_on:
      - redis
    working_dir: /data/osuweb
    volumes:
      - .:/data/osuweb
    user: ${UID:?err}
    environment:
      <<: *x-env
    command: ./docker/notification-server/start.sh
  dependencies:
    build:
      context: ./docker/dependencies
    volumes:
      - .:/data/osuweb
      - ./sql:/data/osuweb/sql
      - ./beatmaps:/data/osuweb/beatmaps
    depends_on:
      - db
    environment:
      <<: *x-env
    user: ${UID:?err}
    working_dir: /data/osuweb
    command: ['./docker/dependencies/start.sh', 'db:3306']
  diffcalc:
    image: microsoft/dotnet:sdk
    volumes:
      - ./osu-server:/data
      - ./beatmaps:/beatmaps
      - ./docker/diffcalc/run.sh:/data/run.sh
    depends_on:
      - db
    working_dir: /data
    environment:
      <<: *x-env
      THREADS: 8
    command: [ './run.sh' ]
  ppcalc:
    build:
      context: ./docker/ppcalc
    volumes:
      - ./osu-performance:/data
      - ./docker/ppcalc/run.sh:/data/run.sh
    depends_on:
      - db
    working_dir: /data
    environment:
      <<: *x-env
      THREADS: 8
    command: [ './run.sh' ]
  esindexer:
    image: microsoft/dotnet:sdk
    volumes:
      - ./osu-elastic-indexer:/data
      - ./docker/esindexer/run.sh:/data/run.sh
    depends_on:
      - db
    working_dir: /data
    environment:
      <<: *x-env
    command: [ './run.sh' ]

volumes:
  database:
  elasticsearch:
